FROM ubuntu:20.04
RUN apt-get update &&\
    apt-get install -y wget &&\
    wget --no-check-certificate https://release.gitkraken.com/linux/gitkraken-amd64.deb
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y ./gitkraken-amd64.deb
RUN apt-get install -y sudo;\
    adduser --home /home/whynotea --disabled-password --gecos "" whynotea;\
    usermod -aG sudo whynotea
RUN rm -rf /usr/share/fonts /usr/local/share/fonts
RUN apt-get install -y fonts-firacode
CMD ["/bin/bash"]
